_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.8
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 55
            "4": 3.10.8
            "5": 0.20.1
            "8":
                - 1
            "12": 0.20.1
            "13": darwin-arm64
alpha:
    value: 0.3
altitude_space_end:
    value: 2.5
altitude_space_num:
    value: 30
altitude_space_start:
    value: 0
episodes:
    value: 3000
epsilon:
    value: 0.99
gamma:
    value: 0.8
runway_distance_space_end:
    value: 1
runway_distance_space_num:
    value: 20
runway_distance_space_start:
    value: -1
target_altitude_space_end:
    value: 1
target_altitude_space_num:
    value: 10
target_altitude_space_start:
    value: 0
vertical_velocity_space_end:
    value: 3
vertical_velocity_space_num:
    value: 20
vertical_velocity_space_start:
    value: -3
