_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.8
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 55
            "4": 3.10.8
            "5": 0.20.1
            "8":
                - 1
            "12": 0.20.1
            "13": darwin-arm64
alpha:
    value: 0.9
episodes:
    value: 6000
epsilon:
    value: 0.99
gamma:
    value: 0.9
